name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, gd, zip
          ini-values: max_execution_time=600, memory_limit=-1
          coverage: xdebug
      - name: Validate composer.json
        run: |
          curl -sS https://getcomposer.org/installer | php -- --filename=composer
          composer validate
      - name: Install dependency
        run: |
          composer install
      - name: Check code standart
        run: |
          composer check-style
      - name: Analyze code
        run: |
          composer check-static-analyze
      - name: Run tests
        run: |
          composer unit
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
      - name: Run integration tests
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_DOMAIN_NAME: ${{ secrets.TEST_DOMAIN_NAME }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          SERVICE_API_KEY: ${{ secrets.SERVICE_API_KEY }}
        run: |
          composer integration

